#!/usr/bin/env python
import os
import sys
import argparse
import logging
from daemoncxt.runner import DaemonRunner
from picostack.deamon_app import (get_picostack_app, getBasicLogger)


USER_HOME_DIR = os.path.expanduser('~/')
VM_MANAGER = 'KVM'
APP_NAME = 'picostk'
CONF_NAME = APP_NAME + '.conf'
DEBUG = True
APP_BIN_DIR = os.path.dirname(os.path.abspath(__file__))
logger = getBasicLogger(APP_NAME, logging.DEBUG)
is_interactive = False


def run_as_daemon(args):
    picostack_app = get_plato_app()    
    if not is_interactive:        
        app_argv = [sys.argv[0], args.action]
        daemon_runner = DaemonRunner(plato_app, app_argv)
        daemon_runner.do_action()
    else:
        plato_app.run()
